[package]
name = "pd_proto"
version = "0.6.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pd_proto"
crate-type = ["cdylib"]

[dependencies]
flate2 = { version = "1.1.10", features = ["zlib-ng"] }
pyo3 = "0.29.2"
mimalloc = "0.1.52"
pyo3-file = "0.17.0"
memmap2 = "0.9.11"
simd-adler32 = "0.3.10"
