[build-system]
requires = ["maturin>=1.9.4,<2"]
build-backend = "maturin"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[project]
name = "pd_proto"
version = "0.5.0"
description = "Binary protocol special for python with efforts to speed and size"
readme = "README.md"
authors = [{ name = "kotolex", email = "farofwell@gmail.com" }]
license = "AGPL-3.0-only OR LicenseRef-Proprietary"
license-files = ["LICENSE"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Education",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = ["binary", "python", "protocol", "pd_proto", "PeaceData", "PDProto"]
dependencies = []
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/kotolex/pd_proto"

