name: Python tests2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tests_and_lint:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/pyo3/maturin:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Tests in Maturin Container
        uses: docker://ghcr.io/pyo3/maturin:latest
        with:
          args: >
            sh -c "
            cargo test --verbose &&
            pip install pylint &&
            python3 -m pylint --rcfile pylint.toml . &&
            maturin develop --release -- -C target-cpu=native &&
            python3 -m unittest discover -s tests
            "
