name: Python tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tests_and_lint:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/pyo3/maturin:latest

    steps:
      - uses: actions/checkout@v4
#      - name: Cache Rust dependencies
#        uses: swatinem/rust-cache@v2
      - name: Run Rust unit tests
        run: cargo test --verbose
      - name: Install dependencies
        run: |
          pip install pylint
      - name: Lint
        run: |
          python -m pylint --rcfile pylint.toml .
      - name: Maturin
        run: |
          maturin develop --release -- -C target-cpu=native
      - name: Unit-tests
        run: |
          python -m unittest discover -s tests